apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: portal
  namespace: portal
spec:
  secretName: sqle.com
  dnsNames:
  - www.sqle.com
  - sqle.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - www.sqle.com
      - sqle.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
