apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: phpmyadmin-c007.cloudclusters.net
  namespace: phpmyadmin
spec:
  secretName: phpmyadmin-c007.cloudclusters.net
  dnsNames:
  - phpmyadmin-c007.cloudclusters.net
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - phpmyadmin-c007.cloudclusters.net
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer

